// react_client/src/components/OrderComponent/OrderCategories.jsx
import React, { useState, useEffect } from 'react';
import CategoriesService from '../../api/services/CategoriesService';
import { useNavigate } from 'react-router-dom';
import LoaderComponent from '../LoaderComponent';

const OrderCategories = ({ ...props }) => {
    const [categories, setCategories] = useState([]);
    const [loading, setLoading] = useState(false);

    const navigate = useNavigate();

    useEffect(() => {
        setLoading(true);
        const fetchData = async () => {
            CategoriesService.getAllCategories()
                .then(response => {
                    setCategories(response);
                })
                .catch(errors => {
                    console.error(errors)
                })
                .finally(ev => {
                    setLoading(false);
                });
        };

        fetchData();
    }, []);

    return (
        loading
            ? (<LoaderComponent />)
            : (<div className="frow order-row">
                <div className="main">
                    {categories.length ? (
                        categories.map((category, index) => (
                            <div key={index} className="card waves-effect pointer" onClick={() => navigate('/order/' + category._id, { props: true })}>
                                <div className="center">
                                    <img src={category.image} alt="imageSrc" className="responsive-img order-img" />
                                </div>
                                <div className="card-content center p10">
                                    <h5 className="m0">{category.name}</h5>
                                </div>
                            </div>
                        ))
                    ) : (
                        <span className="center">No hay Categorías.</span>
                    )}
                </div>
            </div>)
    );
};

export default OrderCategories;

// angular_client/src/app/modules/order/component/order-categories/order-categories.component.ts
import { Component, OnInit } from "@angular/core";
import { RouterPathsEnum } from "../../../../shared/enums/routerPaths.enum";
import { CategoriesService } from "../../../../shared/services/categories/categories.service";
import { delay, Observable } from "rxjs";
import { CategoryInterface } from "../../../../shared/interfaces/category.interface";

@Component({
      selector: "app-order-categories",
      templateUrl: "./order-categories.component.html",
      styleUrls: ["./order-categories.component.css"],
})
export class OrderCategoriesComponent implements OnInit {
      routerPathsEnum = RouterPathsEnum;
      categories$!: Observable<CategoryInterface[]>;
      constructor(private categoriesService: CategoriesService) { }
      trackByIndex(index: number) {
            return index;
      }

      ngOnInit(): void {
            this.categories$ = this.categoriesService
                  .getAllCategories()
                  .pipe(delay(800));
      }
}

<ng-container *ngIf="categories$ | async as categories; else loading">
      <div class="frow order-row">
            <ng-container *ngIf="categories.length; else empty">
                  <div
                        class="card waves-effect pointer"
                        *ngFor="
                              let category of categories;
                              trackBy: trackByIndex
                        "
                        [routerLink]="[
                              '/',
                              routerPathsEnum.ORDER,
                              category._id
                        ]">
                        <div class="center">
                              <img
                                    [src]="category.image"
                                    class="responsive-img order-img"
                                    [alt]="'imageSrc'" />
                        </div>
                        <div class="card-content center p10">
                              <h5 class="m0">{{ category.name }}</h5>
                        </div>
                  </div>
            </ng-container>
            <ng-template #empty>
                  <span class="center">No tienes ninguna Categoría.</span>
            </ng-template>
      </div>
</ng-container>
<ng-template #loading>
      <crm-loader></crm-loader>
</ng-template>
