// react_client/src/components/OrderComponent/OrderOptions.jsx
import React, { useState, useEffect } from 'react';
import OrderService from '../../api/services/OrderService';
import OptionsService from '../../api/services/OptionsService';
import MaterialService from '../../api/services/MaterialService.jsx';
import { useParams } from 'react-router-dom';
import LoaderComponent from '../LoaderComponent.jsx';

const OrderOptions = ({ updateList, setListToOrder }) => {
    const [options, setOptions] = useState([]);
    const [loading, setLoading] = useState(true);

    const { id } = { ...useParams() };

    const consultarApi = async () => {
        if (id === undefined) {
            return;
        }
        setLoading(true);
        try {
            const optionsData = await OptionsService.getAllOptions(id);
            const optionsWithQuantity = optionsData.map((p) => ({ ...p, quantity: 1 }));
            setOptions(optionsWithQuantity);
            setLoading(false);
        } catch (error) {
            MaterialService.toast('Could not retrieve options.');
            setLoading(false);
        }
    };

    useEffect(() => {
        consultarApi();
    }, [id]);

    const addToOrder = (option) => {
        MaterialService.toast(`Opción ${option.name} x${option.quantity} se agregó.`);
        OrderService.add(option);
        updateList([...OrderService.list]);
    };

    return (
        <>
            {
                loading
                    ? <LoaderComponent />
                    : (
                        <table className="highlight">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Precio</th>
                                    <th>Cantidad</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {options.length ? (
                                    options.map((option) => (
                                        <tr key={option._id}>
                                            <td>{option.name}</td>
                                            <td>{option.cost} $</td>
                                            <td>
                                                <div className="input-field inline order-option-input">
                                                    <input value={option.quantity} onChange={(e) => setOptions(options.map((o) => (o._id === option._id ? { ...o, quantity: e.target.value } : o)))} type="number" min="0" />
                                                </div>
                                            </td>
                                            <td>
                                                <button disabled={!option.quantity} onClick={() => addToOrder(option)} className="btn waves-effect wavers-light btn-small">Agregar</button>
                                            </td>
                                        </tr>
                                    ))
                                ) : (
                                    <span className="valign-wrapper">
                                        <i className="material-icons">do_not_disturb_alt</i>No hay opciones
                                    </span>
                                )}
                            </tbody>
                        </table>
                    )
            }
        </>
    );
};

export default OrderOptions;

// angular_client/src/app/modules/order/component/order-options/order-options.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Params } from "@angular/router";
import { map, Observable, switchMap } from "rxjs";
import { OrderService as AppOrdersService } from "../../service/order.service";
import { MaterialService } from "../../../../shared/classes/material.service";
import { OptionWithQuantityInterface } from "src/app/shared/interfaces/option.interface";
import { OptionsService } from "src/app/shared/services/positions/option.service";

@Component({
      selector: "app-order-options",
      templateUrl: "./order-options.component.html",
      styleUrls: ["./order-options.component.css"],
})
export class OrderOptionsComponent implements OnInit {
      options$!: Observable<OptionWithQuantityInterface[]>;
      constructor(
            private optionsService: OptionsService,
            private route: ActivatedRoute,
            private appOrderService: AppOrdersService,
            private materialService: MaterialService,
      ) {}

      ngOnInit(): void {
            this.options$ = this.route.params.pipe(
                  switchMap((params: Params) => {
                        return this.optionsService.getAllOptions(
                              params["id"],
                        );
                  }),
                  map(options => options.map(p => ({ ...p, quantity: 1 }))),
            );
      }

      addToOrder(option: OptionWithQuantityInterface) {
            this.materialService.toast(
                  `La Opción ${option.name} x${option.quantity} fue agregada.`,
            );
            this.appOrderService.add(option);
      }
}

<table class="highlight">
      <ng-container *ngIf="options$ | async as options; else loading">
            <thead>
                  <tr>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Cantidad</th>
                        <th></th>
                  </tr>
            </thead>
            <tbody>
                  <ng-container *ngIf="options.length; else empty">
                        <tr *ngFor="let option of options">
                              <td>{{ option.name }}</td>
                              <td>{{ option.cost }} $</td>
                              <td>
                                    <div
                                          class="input-field inline order-option-input">
                                          <input
                                                [(ngModel)]="option.quantity"
                                                type="number"
                                                min="0" />
                                    </div>
                              </td>
                              <td>
                                    <button
                                          class="btn waves-effect wavers-light btn-small"
                                          [disabled]="!option.quantity"
                                          (click)="addToOrder(option)"
                                          >Agregar</button
                                    >
                              </td>
                        </tr>
                  </ng-container>
                  <ng-template #empty>
                        <span class="valign-wrapper">
                              <i class="material-icons">do_not_disturb_alt</i>No hay opciones
                        </span>
                  </ng-template>
            </tbody>
      </ng-container>
      <ng-template #loading>
            <crm-loader></crm-loader>
      </ng-template>
</table>
