// angular_client/src/app/modules/history/components/history-list/history-list/history-list.component.ts
import { AfterViewInit, Component, ElementRef, EventEmitter, Input, OnDestroy, Output, ViewChild, OnInit } from "@angular/core";
import { MaterialInterface, MaterialService } from "../../../../../shared/classes/material.service";
import { OrderInterface } from "src/app/shared/interfaces/option.interface";
import { OrderService } from "src/app/modules/order/service/order.service";
import { Subject, takeUntil } from "rxjs";
import { AuthService } from "src/app/shared/services/auth/auth.service";

@Component({
      selector: "crm-history-list",
      templateUrl: "./history-list.component.html",
      styleUrls: ["./history-list.component.css"],
})
export class HistoryListComponent implements OnInit, AfterViewInit, OnDestroy {
      modalWindow!: MaterialInterface;
      selectedOrder!: OrderInterface;
      isAdmin: boolean = false;
      @Input("historyList") historyListProps!: OrderInterface[] | null;
      @ViewChild("modal") modalRef!: ElementRef;
      @Output() orderFinished = new EventEmitter<void>();
      @Output() fetch = new EventEmitter<void>();
      private destroy$ = new Subject<void>();
      constructor(
            private materialService: MaterialService,
            private orderService: OrderService,
            private authService: AuthService,
      ) {
            this.isAdmin = this.authService.isAdmin();
      }

      ngOnInit(): void {
            this.authService.currentUser
                  .pipe(takeUntil(this.destroy$))
                  .subscribe((user) => {
                        this.isAdmin = user?.admin === true;
                  });
      }

      selectOrder(item: OrderInterface) {
            this.selectedOrder = item;
            this.modalWindow.open();
      }

      calculateTotalCost(historyItem: OrderInterface): number {
            return historyItem.list.reduce((acc, el) => {
                  return (acc += el.quantity ? el.cost * el.quantity : el.cost);
            }, 0);
      }

      trackById(index: number, item: OrderInterface) {
            return item._id;
      }

      ngAfterViewInit(): void {
            this.modalWindow = this.materialService.initModal(
                  this.modalRef.nativeElement,
            );
      }

      finishOrder() {
            if (this.selectedOrder && this.selectedOrder._id) {
                  this.orderService.finishOrder(this.selectedOrder._id).subscribe({
                        next: (updatedOrder) => {
                              this.selectedOrder = updatedOrder;
                              this.materialService.toast('Orden finalizada!');
                              this.closeModal();
                              this.orderFinished.emit();
                        },
                        error: (err) => {
                              this.materialService.toast('Error al finalizar la orden');
                        }
                  });
            } else {
                  this.materialService.toast('La orden seleccionada no tiene un ID válido.');
            }
      }

      closeModal() {
            this.fetch.emit();
            this.modalWindow.close();
      }

      ngOnDestroy(): void {
            this.modalWindow.destroy();
            this.destroy$.next();
            this.destroy$.complete();
      }
}

<table class="highlight mb2">
      <thead>
            <tr>
                  <th>№</th>
                  <th>Fecha</th>
                  <th>Hora</th>
                  <th>Total</th>
                  <th>Estado</th>
                  <th></th>
            </tr>
      </thead>

      <tbody>
            <tr
                  *ngFor="
                        let historyItem of historyListProps;
                        trackBy: trackById
                  ">
                  <td>{{ historyItem.order }}</td>
                  <td>{{ historyItem.date | date : "dd/MM/yyyy" }}</td>
                  <td>{{ historyItem.date | date : "HH:mm:ss" }}</td>
                  <td>{{ calculateTotalCost(historyItem) }} $</td>
                  <td>{{ historyItem.status == 'Pending' ? 'Iniciada' : 'Finalizada' }}</td>
                  <td>
                        <button
                              (click)="selectOrder(historyItem)"
                              class="btn btn-small grey darken-1">
                              <i class="material-icons">open_in_new</i>
                        </button>
                  </td>
            </tr>
      </tbody>
</table>

<div #modal class="modal modal-fixed-footer">
      <div class="modal-content" *ngIf="selectedOrder">
            <h4 class="mb1">Pedido №{{ selectedOrder.order }}</h4>
            <table class="highlight">
                  <thead>
                        <tr>
                              <th>Nombre</th>
                              <th>Cantidad</th>
                              <th>Precio</th>
                        </tr>
                  </thead>

                  <tbody>
                        <tr *ngFor="let item of selectedOrder.list">
                              <td>{{ item.name }}</td>
                              <td>{{ item.quantity }}</td>
                              <td>${{ item.cost }}</td>
                        </tr>
                  </tbody>
            </table>
            <div class="order-summary">
                  <p
                        >Total
                        <strong
                              >{{ calculateTotalCost(selectedOrder) }} $</strong
                        ></p
                  >
            </div>
      </div>
      <div class="modal-footer">
            <button class="btn waves-effect grey darken-1 btn-small" *ngIf="isAdmin && selectedOrder?.status == 'Pending'" (click)="finishOrder()">Finalizar</button>
            <button
                  class="modal-action waves-effect waves-black btn-flat"
                  (click)="closeModal()"
                  >cerrar</button
            >
      </div>
</div>

// react_client/src/components/HistoryComponent/HistoryList.jsx
import React, { useEffect, useState, useRef } from 'react';
import OrderService from '../../api/services/OrderService';
import MaterialService from '../../api/services/MaterialService';
import calculateTotalCost from '../../utils/calculateTotalCost';
import ModalComponent from './ModalHistoryComponent';
import LoaderComponent from '../LoaderComponent';

function HistoryListComponent({ historyList, orderFinished, openModal, modalRef, closeModal, selectedOrder, setSelectedOrder, isModalOpen, isAdmin, loadingFlag }) {
    const [] = useState(null);
    const destroy$ = useRef({ next: () => { }, complete: () => { } });

    useEffect(() => {
        return () => {
            destroy$.current.next();
            destroy$.current.complete();
        };
    }, []);

    const selectOrder = (item) => {
        setSelectedOrder(prev => prev = {...item});
        openModal();
    };

    const trackById = (index, item) => {
        return item._id;
    };

    const finishOrder = () => {
        if (selectedOrder && selectedOrder._id) {
            return OrderService.finishOrder(selectedOrder._id)
            .then(response => {
                    MaterialService.toast('Orden finalizada!');
                    closeModal();
                    orderFinished();
                }).catch(errors => {
                    console.error(errors);
                    MaterialService.toast('Error al finalizar la orden');
                })
        } else {
            MaterialService.toast('La orden seleccionada no tiene un ID válido.');
        }
    };

    return (
        <>

            <table className="highlight mb2">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Total</th>
                        <th>Estado</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {historyList.map((historyItem) => (
                        <tr key={historyItem._id}>
                            <td>{historyItem.order}</td>
                            <td>{new Date(historyItem.date).toLocaleDateString()}</td>
                            <td>{new Date(historyItem.date).toLocaleTimeString()}</td>
                            <td>{calculateTotalCost(historyItem)} $</td>
                            <td>
                                {historyItem.status === 'Pending' ? 'Iniciada' : 'Finalizada'}
                            </td>
                            <td>
                                <button
                                    onClick={() => { selectOrder(historyItem) }}
                                    className="btn btn-small grey darken-1"
                                >
                                    <i className="material-icons">open_in_new</i>
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
            {
                loadingFlag && <LoaderComponent />
            }
            <ModalComponent
                modalRef={modalRef}
                selectedOrder={selectedOrder}
                isAdmin={isAdmin}
                finishOrder={finishOrder}
                closeModal={closeModal}
            />

        </>
    );
}

export default HistoryListComponent;
