// angular_client/src/app/modules/history/components/history.component.ts
import {
      AfterViewInit,
      Component,
      ElementRef,
      OnDestroy,
      OnInit,
      ViewChild,
} from "@angular/core";
import { OrdersService as HttpOrdersService, OrdersService } from "../../../shared/services/orders/orders.service";
import { Subject, takeUntil } from "rxjs";
import { environment } from "../../../../enviroments/environment";
import { OrderInterface } from "src/app/shared/interfaces/option.interface";
import { AuthService } from "../../../shared/services/auth/auth.service";

@Component({
      selector: "crm-history",
      templateUrl: "./history.component.html",
      styleUrls: ["./history.component.css"],
})
export class HistoryComponent implements AfterViewInit, OnInit, OnDestroy {
      showFilter = false;
      offset = 0;
      limit = environment.STEP;
      historyList: OrderInterface[] = [];
      isAlive = new Subject<void>();
      @ViewChild("tooltip") tooltipRef: ElementRef | undefined;
      loadingFlag = false;
      reloadingFlag = false;
      noMoreFlag = false;
      constructor(
            private ordersService: OrdersService,
            private authService: AuthService,
      ) { }

      reloadContent() {
            this.historyList = [];
            this.offset = 0;
            this.reloadingFlag = true;
            this.fetch();
      }

      onOrderFinished() {
            this.reloadContent();
      }

      loadMore() {
            this.loadingFlag = true;
            this.limit += environment.STEP;
            this.fetch();
      }

      ngAfterViewInit(): void {
      }

      ngOnDestroy(): void {
            this.isAlive.next();
            this.isAlive.complete();
      }

      ngOnInit(): void {
            this.reloadingFlag = true;
            this.fetch();
      }

      fetch(): void {
            const params: { offset: number; limit: number } = {
                  offset: this.offset,
                  limit: this.limit,
            };

            if (this.authService.isAdmin()) {
                  this.ordersService.getAllOrders(params)
                        .pipe(takeUntil(this.isAlive))
                        .subscribe(
                              (orders: OrderInterface[]) => {
                                    this.historyList = orders;
                                    this.loadingFlag = false;
                                    this.reloadingFlag = false;
                                    this.noMoreFlag = orders.length < this.limit;
                              },
                              (error: Error) => {
                                    console.error('Error obteniendo las Órdenes:', error);
                              }
                        );
            } else {
                  const currentUserId = localStorage.getItem('userDetails');
                  if (currentUserId && currentUserId !== null) {
                        const userData = JSON.parse(currentUserId);
                        this.ordersService.getOrdersByUser(userData._id, params)
                              .pipe(takeUntil(this.isAlive))
                              .subscribe(
                                    (orders: OrderInterface[]) => {
                                          this.historyList = orders;
                                          this.loadingFlag = false;
                                          this.reloadingFlag = false;
                                          this.noMoreFlag = orders.length < this.limit;
                                    },
                                    (error: Error) => {
                                          console.error('Error obteniendo las Órdenes:', error);
                                    }
                              );
                  } else {
                        console.error('Error obteniendo las Órdenes: ID del usuario es undefined.');
                  }
            }
      }

}

<main class="content">
      <div class="page-title">
            <h4>Historial de Pedidos</h4>
            <button (click)="reloadContent()" class="btn btn-small" [disabled]="reloadingFlag" data-tooltip="Recargar">
                  <i class="material-icons">refresh</i>
            </button>
      </div>


      <div class="card">
            <div class="card-content">
                  <ng-container *ngIf="!reloadingFlag; else reloading">
                        <ng-container *ngIf="historyList.length; else empty">
                              <crm-history-list [historyList]="historyList" (orderFinished)="onOrderFinished()"
                                    (fetch)="fetch()"></crm-history-list>
                        </ng-container>
                        <ng-template #empty>
                              <div class="center">No hay pedidos</div>
                        </ng-template>
                        <div class="center mb2" *ngIf="!noMoreFlag">
                              <button [disabled]="noMoreFlag" *ngIf="!loadingFlag; else loading"
                                    class="btn waves-effect grey darken-1 btn-small" (click)="loadMore()">Cargar
                                    más</button>
                              <ng-template #loading>
                                    <crm-loader></crm-loader>
                              </ng-template>
                        </div>
                  </ng-container>
            </div>
      </div>
      <ng-template #reloading>
            <crm-loader></crm-loader>
      </ng-template>
</main>

// react_client/src/components/HistoryComponent/History.jsx
import React, { useEffect, useRef, useState } from 'react';
import HistoryList from './HistoryList';
import { environment } from '../../enviroments/environment';
import OrderService from '../../api/services/OrderService';
import AuthService from '../../api/services/AuthService';
import './styles.css'
import MaterialService from '../../api/services/MaterialService';
import LoaderComponent from '../LoaderComponent';

function HistoryComponent() {
    const [offset, setOffset] = useState(0);
    const [limit, setLimit] = useState(environment.STEP);
    const [historyList, setHistoryList] = useState([]);
    const [noMoreFlag, setNoMoreFlag] = useState(false);
    const [loadingFlag, setLoadingFlag] = useState(false);
    const [reloadingFlag, setReloadingFlag] = useState(false);
    const modalRef = useRef(null);

    const [selectedOrder, setSelectedOrder] = useState(null);

    const currentUser = AuthService.getCurrentUser();

    useEffect(() => {
        setReloadingFlag(true);
    }, [])


    useEffect(() => {
        fetchHistory();
    }, [limit]);

    const reloadContent = () => {
        setReloadingFlag(true);
        setHistoryList([]);
        fetchHistory();
    };

    const onOrderFinished = () => {
        return reloadContent();
    };

    const loadMore = () => {
        setLoadingFlag(true)
        setLimit(prev => prev = prev + environment.STEP)
    };

    const fetchHistory = () => {
        const params = { offset, limit };
        if (currentUser.admin) {
            OrderService.getAllOrders({ ...params })
                .then((response) => {
                    setNoMoreFlag(response.length < limit);
                    setReloadingFlag(false);
                    setLoadingFlag(false);
                    setHistoryList([...response]);
                })
                .catch((error) => {
                    setReloadingFlag(false);
                    setLoadingFlag(false);
                    console.error('Error obteniendo Órdenes:', error);
                });
        } else {
            OrderService.getOrdersByUser({ userId: currentUser._id, ...params })
                .then((response) => {
                    setNoMoreFlag(response.length < limit);
                    setReloadingFlag(false);
                    setLoadingFlag(false);
                    setHistoryList([...response]);
                })
                .catch((error) => {
                    setReloadingFlag(false);
                    setLoadingFlag(false);
                    console.error('Error obteniendo Órdenes:', error);
                });
        }
    };

    const openModal = () => {
        const modalInstance = MaterialService.M.Modal.init(modalRef.current);
        modalInstance.open();
    };

    const closeModal = () => {
        const modalInstance = MaterialService.M.Modal.init(modalRef.current);
        modalInstance.close();
    };


    return (
        <>
            <main className="content">
                <div className="page-title">
                    <h4>Historial de Pedidos</h4>
                    <button
                        onClick={reloadContent}
                        className="btn btn-small"
                        disabled={reloadingFlag || loadingFlag}
                        data-tooltip="Recargar"
                    >
                        <i className="material-icons">refresh</i>
                    </button>
                </div>
                <div className="card">
                    <div className="card-content">
                        {
                            reloadingFlag
                                ? <LoaderComponent />
                                : <>
                                    {historyList.length ? (
                                        <HistoryList
                                            historyList={historyList}
                                            modalRef={modalRef}
                                            orderFinished={onOrderFinished}
                                            openModal={openModal}
                                            closeModal={closeModal}
                                            selectedOrder={selectedOrder}
                                            setSelectedOrder={setSelectedOrder}
                                            isAdmin={currentUser.admin}
                                            loadingFlag={loadingFlag}
                                        />
                                    ) : (
                                        <div className="center">No hay pedidos</div>
                                    )}
                                    <div className="center mb2" style={{ display: noMoreFlag || loadingFlag || reloadingFlag ? 'none' : 'block' }}>
                                        <button
                                            disabled={noMoreFlag || loadingFlag || reloadingFlag}
                                            onClick={loadMore}
                                            className="btn waves-effect grey darken-1 btn-small"
                                        >
                                            Cargar más
                                        </button>
                                    </div>
                                </>
                        }
                    </div>
                </div>
            </main>
        </>
    );
}

export default HistoryComponent;
