// angular_client/src/app/modules/categories/components/categories.component.ts
import { Component, OnInit } from "@angular/core";
import { RouterPathsEnum } from "../../../shared/enums/routerPaths.enum";
import { CategoriesService } from "../../../shared/services/categories/categories.service";
import { delay, Observable } from "rxjs";
import { CategoryInterface } from "../../../shared/interfaces/category.interface";

@Component({
      selector: "crm-categories",
      templateUrl: "./categories.component.html",
      styleUrls: ["./categories.component.css"],
})
export class CategoriesComponent implements OnInit {
      categoriesList$!: Observable<CategoryInterface[]>;
      routerPathsEnum = RouterPathsEnum;

      constructor(private categoriesService: CategoriesService) {}

      trackById(index: number, item: CategoryInterface) {
            return item._id;
      }

      ngOnInit(): void {
            this.categoriesList$ = this.categoriesService
                  .getAllCategories()
                  .pipe(delay(800));
      }
}

<main class="content">
      <div class="page-title">
            <h4>Categorías</h4>
            <button
                  class="waves-effect waves-light btn grey darken-1"
                  [routerLink]="routerPathsEnum.NEW"
                  >Agregar categoría</button
            >
      </div>

      <div class="row">
            <div class="col s12">
                  <ng-container
                        *ngIf="
                              categoriesList$ | async as categories;
                              else loading
                        ">
                        <ng-container *ngIf="categories.length; else empty">
                              <div class="collection">
                                    <a
                                          *ngFor="
                                                let category of categories;
                                                trackBy: trackById
                                          "
                                          [routerLink]="[category._id]"
                                          class="collection-item"
                                          >{{ category.name }}</a
                                    >
                              </div>
                        </ng-container>
                        <ng-template #empty>
                              <span class="valign-wrapper">
                                    No tienes categorías.
                                    <i class="material-icons">shopping_cart</i>
                              </span>
                        </ng-template>
                  </ng-container>
                  <ng-template #loading>
                        <crm-loader></crm-loader>
                  </ng-template>
            </div>
      </div>
</main>

// react_client/src/components/CategoryComponent/Categories.jsx
import React, { useEffect, useState } from 'react';
import { RouterPathsEnum } from '../../api/enums/routerPaths.enum.tsx';
import { useNavigate, Link } from 'react-router-dom';
import LoaderComponent from '../LoaderComponent.jsx';
import CategoriesService from '../../api/services/CategoriesService.jsx';

function Categories() {
    const [categories, setCategories] = useState(null);
    const [loading, setLoading] = useState(false);
    const routerPathsEnum = RouterPathsEnum;

    const navigate = useNavigate()

    useEffect(() => {
        setLoading(true);
        CategoriesService.getAllCategories()
            .then(response => {
                setCategories(prev => response)
            })
            .catch(errors => console.error(errors))
            .finally(ev => setLoading(false));
    }, []);

    return (
        <main className="content">
            <div className="page-title">
                <h4>Categorías</h4>
                <button className="waves-effect waves-light btn grey darken-1" onClick={() => navigate(routerPathsEnum.NEW)}>
                    Agregar categoría
                </button>
            </div>

            {
                loading
                    ? <LoaderComponent />
                    : <div className="row">
                        <div className="col s12">
                            {categories ? (
                                <>
                                    {categories.length ? (
                                        <div className="collection">
                                            {categories.map((category) => (
                                                <Link
                                                    key={category._id}
                                                    to={'/categories/'+category._id}
                                                    className="collection-item"
                                                >
                                                    {category.name}
                                                </Link>
                                            ))}
                                        </div>
                                    ) : (
                                        <span className="valign-wrapper">
                                            No tienes categorías.
                                            <i className="material-icons">shopping_cart</i>
                                        </span>
                                    )}
                                </>
                            ) : (
                                <LoaderComponent />
                            )}
                        </div>
                    </div>
            }
        </main>
    );
}

export default Categories;
