// angular_client/src/app/modules/categories/components/category-form/confirm-dialog/confirm-dialog.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-confirm-category-dialog',
  template: `
    <h1 mat-dialog-title>Confirma</h1>
    <div mat-dialog-content>
      <p>¿Confirmas que vas a eliminar esta categoría?</p>
    </div>
    <div mat-dialog-actions>
      <button mat-button [mat-dialog-close]="true">Sí</button>
      <button mat-button [mat-dialog-close]="false">No</button>
    </div>
  `,
})
export class ConfirmCategoryDialogComponent { }

// react_client/src/components/CategoryComponent/ConfirmDialog.jsx
import React from 'react';

function ConfirmDialog() {
    return (
        <div>
            <h1>Confirma</h1>
            <div>
                <p>¿Confirmas que vas a eliminar esta categoría?</p>
            </div>
            <div>
                <button>Sí</button>
                <button>No</button>
            </div>
        </div>
    );
}

export default ConfirmDialog;
